name = "housemanager"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

[vars]
  DATABASE_URL=""
  GOOGLE_API_KEY=""

[site]
  bucket = "./public"

[build]
  command = "npm run build"