name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma models
        run: npm run prisma:generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            DATABASE_URL
            GOOGLE_API_KEY
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_API_KEY: ${{secrets.GOOGLE_API_KEY}}
